//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift open source project
//
// Copyright (c) 2025 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See http://swift.org/LICENSE.txt for license information
// See http://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

import Foundation
@testable import SBOMModel

extension SBOMTestDependencyGraph {
    static func createSwiftlyDependencyGraph() -> [String: [String]] {
        [
            "NIOSSL": [
                "swift-nio-ssl_NIOSSL",
                "CNIOBoringSSL",
                "CNIOBoringSSLShims",
                "NIO-product",
                "NIOCore-product",
                "NIOConcurrencyHelpers-product",
                "NIOTLS-product",
            ],
            "CLibArchive": [],
            "build-swiftly-release-product": [
                "OpenAPIGenerator-product",
                "SwiftlyDownloadAPI",
                "SwiftlyWebsiteAPI",
                "generate-command-models-product",
                "GenerateCommandModels",
                "SwiftlyCore",
                "CLibArchive",
                "MacOSPlatform",
                "OpenAPIRuntime-product",
                "ArgumentParser-product",
                "SystemPackage-product",
                "AsyncHTTPClient-product",
                "NIOFoundationCompat-product",
                "OpenAPIAsyncHTTPClient-product",
                "Subprocess-product",
                "_NIOFileSystem-product",
            ],
            "OpenAPIGenerator": [
                "_OpenAPIGeneratorCore",
                "swift-openapi-generator-product",
                "OpenAPIKit-product",
                "OpenAPIKit30-product",
                "OpenAPIKitCompat-product",
                "Algorithms-product",
                "OrderedCollections-product",
                "Yams-product",
                "ArgumentParser-product",
            ],
            "_NumericsShims": [],
            "NIOEmbedded": [
                "CNIOAtomics",
                "NIOConcurrencyHelpers",
                "_NIOBase64",
                "CNIODarwin",
                "CNIOLinux",
                "CNIOWindows",
                "CNIOWASI",
                "_NIODataStructures",
                "NIOCore",
                "DequeModule-product",
                "Atomics-product",
            ],
            "HTTPTypes-product": ["HTTPTypes"],
            "generate-command-models": ["ArgumentParser-product", "SystemPackage-product"],
            "NIO": [
                "CNIOAtomics",
                "NIOConcurrencyHelpers",
                "_NIOBase64",
                "CNIODarwin",
                "CNIOLinux",
                "CNIOWindows",
                "CNIOWASI",
                "_NIODataStructures",
                "NIOCore",
                "NIOEmbedded",
                "CNIOPosix",
                "NIOPosix",
                "DequeModule-product",
                "Atomics-product",
            ],
            "ArgumentParser": ["ArgumentParserToolInfo"],
            "swift-nio_NIOPosix": [],
            "AsyncHTTPClient-product": [
                "AsyncHTTPClient",
                "CAsyncHTTPClient",
                "NIO-product",
                "NIOTLS-product",
                "NIOCore-product",
                "NIOPosix-product",
                "NIOHTTP1-product",
                "NIOConcurrencyHelpers-product",
                "NIOHTTP2-product",
                "NIOSSL-product",
                "NIOHTTPCompression-product",
                "NIOSOCKS-product",
                "NIOTransportServices-product",
                "Atomics-product",
                "Algorithms-product",
                "Logging-product",
                "Tracing-product",
            ],
            "RealModule": ["_NumericsShims"],
            "OpenAPIKit30-product": ["OpenAPIKit30", "OpenAPIKitCore"],
            "swiftly-product": [
                "OpenAPIGenerator-product",
                "SwiftlyDownloadAPI",
                "SwiftlyWebsiteAPI",
                "generate-command-models-product",
                "GenerateCommandModels",
                "SwiftlyCore",
                "CLibArchive",
                "MacOSPlatform",
                "OpenAPIRuntime-product",
                "ArgumentParser-product",
                "SystemPackage-product",
                "AsyncHTTPClient-product",
                "NIOFoundationCompat-product",
                "OpenAPIAsyncHTTPClient-product",
                "Subprocess-product",
                "SwiftToolsSupport-auto-product",
            ],
            "TSCclibc": [],
            "Subprocess-product": ["Subprocess", "_SubprocessCShims", "SystemPackage-product"],
            "OpenAPIRuntime-product": ["OpenAPIRuntime", "HTTPTypes-product"],
            "swift-nio__NIOFileSystem": [],
            "NIOConcurrencyHelpers": ["CNIOAtomics"],
            "SwiftlyCore": [
                "OpenAPIGenerator-product",
                "SwiftlyDownloadAPI",
                "SwiftlyWebsiteAPI",
                "generate-command-models-product",
                "GenerateCommandModels",
                "OpenAPIRuntime-product",
                "ArgumentParser-product",
                "SystemPackage-product",
                "AsyncHTTPClient-product",
                "NIOFoundationCompat-product",
                "OpenAPIAsyncHTTPClient-product",
                "Subprocess-product",
            ],
            "SwiftlyDownloadAPI": ["OpenAPIGenerator-product", "OpenAPIRuntime-product"],
            "CNIOBoringSSL": [],
            "swift-openapi-generator-product": [
                "_OpenAPIGeneratorCore",
                "OpenAPIKit-product",
                "OpenAPIKit30-product",
                "OpenAPIKitCompat-product",
                "Algorithms-product",
                "OrderedCollections-product",
                "Yams-product",
                "ArgumentParser-product",
            ],
            "Yams-product": ["Yams", "CYaml"],
            "NIOTransportServices-product": [
                "NIOTransportServices",
                "NIO-product",
                "NIOCore-product",
                "NIOFoundationCompat-product",
                "NIOTLS-product",
                "Atomics-product",
            ],
            "test-swiftly-product": [
                "OpenAPIGenerator-product",
                "SwiftlyDownloadAPI",
                "SwiftlyWebsiteAPI",
                "generate-command-models-product",
                "GenerateCommandModels",
                "SwiftlyCore",
                "CLibArchive",
                "MacOSPlatform",
                "OpenAPIRuntime-product",
                "ArgumentParser-product",
                "SystemPackage-product",
                "AsyncHTTPClient-product",
                "NIOFoundationCompat-product",
                "OpenAPIAsyncHTTPClient-product",
                "Subprocess-product",
            ],
            "_NIOFileSystem": [
                "swift-nio__NIOFileSystem",
                "CNIOAtomics",
                "NIOConcurrencyHelpers",
                "_NIOBase64",
                "CNIODarwin",
                "CNIOLinux",
                "CNIOWindows",
                "CNIOWASI",
                "_NIODataStructures",
                "NIOCore",
                "CNIOPosix",
                "NIOPosix",
                "DequeModule-product",
                "Atomics-product",
                "SystemPackage-product",
            ],
            "CAsyncHTTPClient": [],
            "GenerateDocsReference": ["generate-docs-reference-product", "ArgumentParser-product"],
            "SwiftToolsSupport-auto-product": ["TSCBasic", "TSCUtility", "TSCLibc", "TSCclibc"],
            "TestSwiftly": [
                "OpenAPIGenerator-product",
                "SwiftlyDownloadAPI",
                "SwiftlyWebsiteAPI",
                "generate-command-models-product",
                "GenerateCommandModels",
                "SwiftlyCore",
                "CLibArchive",
                "MacOSPlatform",
                "OpenAPIRuntime-product",
                "ArgumentParser-product",
                "SystemPackage-product",
                "AsyncHTTPClient-product",
                "NIOFoundationCompat-product",
                "OpenAPIAsyncHTTPClient-product",
                "Subprocess-product",
            ],
            "SwiftlyWebsiteAPI": ["OpenAPIGenerator-product", "OpenAPIRuntime-product"],
            "OpenAPIKitCompat": ["OpenAPIKitCore", "OpenAPIKit30", "OpenAPIKit"],
            "NIOConcurrencyHelpers-product": ["NIOConcurrencyHelpers", "CNIOAtomics"],
            "SystemPackage-product": ["SystemPackage", "CSystem"],
            "DequeModule": ["InternalCollectionsUtilities"],
            "NIOCore": [
                "CNIOAtomics",
                "NIOConcurrencyHelpers",
                "_NIOBase64",
                "CNIODarwin",
                "CNIOLinux",
                "CNIOWindows",
                "CNIOWASI",
                "_NIODataStructures",
                "DequeModule-product",
                "Atomics-product",
            ],
            "NIOHTTP1-product": [
                "NIOHTTP1",
                "CNIOAtomics",
                "NIOConcurrencyHelpers",
                "_NIOBase64",
                "CNIODarwin",
                "CNIOLinux",
                "CNIOWindows",
                "CNIOWASI",
                "_NIODataStructures",
                "NIOCore",
                "NIOEmbedded",
                "CNIOPosix",
                "NIOPosix",
                "NIO",
                "CNIOLLHTTP",
                "DequeModule-product",
                "Atomics-product",
            ],
            "CNIOLLHTTP": [],
            "generate-docs-reference": ["ArgumentParser-product"],
            "CNIOBoringSSLShims": ["CNIOBoringSSL"],
            "CNIOAtomics": [],
            "NIOHTTPCompression-product": [
                "NIOHTTPCompression",
                "CNIOExtrasZlib",
                "NIO-product",
                "NIOCore-product",
                "NIOHTTP1-product",
            ],
            "_NIODataStructures": [],
            "Logging-product": ["Logging"],
            "Algorithms": ["RealModule-product"],
            "NIOSOCKS": ["NIO-product", "NIOCore-product"],
            "SwiftlyDocs": [],
            "OpenAPIKit": ["OpenAPIKitCore"],
            "_NIOBase64": [],
            "OpenAPIRuntime": ["HTTPTypes-product"],
            "GenerateCommandModels": [
                "generate-command-models-product",
                "ArgumentParser-product",
                "SystemPackage-product",
            ],
            "generate-docs-reference-product": ["ArgumentParser-product"],
            "NIOSOCKS-product": ["NIOSOCKS", "NIO-product", "NIOCore-product"],
            "ServiceContextModule-product": ["ServiceContextModule"],
            "MacOSPlatform": [
                "OpenAPIGenerator-product",
                "SwiftlyDownloadAPI",
                "SwiftlyWebsiteAPI",
                "generate-command-models-product",
                "GenerateCommandModels",
                "SwiftlyCore",
                "OpenAPIRuntime-product",
                "ArgumentParser-product",
                "SystemPackage-product",
                "AsyncHTTPClient-product",
                "NIOFoundationCompat-product",
                "OpenAPIAsyncHTTPClient-product",
                "Subprocess-product",
            ],
            "AsyncHTTPClient": [
                "CAsyncHTTPClient",
                "NIO-product",
                "NIOTLS-product",
                "NIOCore-product",
                "NIOPosix-product",
                "NIOHTTP1-product",
                "NIOConcurrencyHelpers-product",
                "NIOHTTP2-product",
                "NIOSSL-product",
                "NIOHTTPCompression-product",
                "NIOSOCKS-product",
                "NIOTransportServices-product",
                "Atomics-product",
                "Algorithms-product",
                "Logging-product",
                "Tracing-product",
            ],
            "TSCLibc": [],
            "OpenAPIKitCompat-product": ["OpenAPIKitCompat", "OpenAPIKitCore", "OpenAPIKit30", "OpenAPIKit"],
            "Subprocess": ["_SubprocessCShims", "SystemPackage-product"],
            "NIOSSL-product": [
                "NIOSSL",
                "swift-nio-ssl_NIOSSL",
                "CNIOBoringSSL",
                "CNIOBoringSSLShims",
                "NIO-product",
                "NIOCore-product",
                "NIOConcurrencyHelpers-product",
                "NIOTLS-product",
            ],
            "TSCUtility": ["TSCLibc", "TSCclibc", "TSCBasic"],
            "NIOPosix": [
                "swift-nio_NIOPosix",
                "CNIOLinux",
                "CNIODarwin",
                "CNIOWindows",
                "CNIOAtomics",
                "NIOConcurrencyHelpers",
                "_NIOBase64",
                "CNIOWASI",
                "_NIODataStructures",
                "NIOCore",
                "CNIOPosix",
                "DequeModule-product",
                "Atomics-product",
            ],
            "swiftly_SwiftlyTests": [],
            "Swiftly": [
                "OpenAPIGenerator-product",
                "SwiftlyDownloadAPI",
                "SwiftlyWebsiteAPI",
                "generate-command-models-product",
                "GenerateCommandModels",
                "SwiftlyCore",
                "CLibArchive",
                "MacOSPlatform",
                "OpenAPIRuntime-product",
                "ArgumentParser-product",
                "SystemPackage-product",
                "AsyncHTTPClient-product",
                "NIOFoundationCompat-product",
                "OpenAPIAsyncHTTPClient-product",
                "Subprocess-product",
                "SwiftToolsSupport-auto-product",
            ],
            "NIOPosix-product": [
                "NIOPosix",
                "swift-nio_NIOPosix",
                "CNIOLinux",
                "CNIODarwin",
                "CNIOWindows",
                "CNIOAtomics",
                "NIOConcurrencyHelpers",
                "_NIOBase64",
                "CNIOWASI",
                "_NIODataStructures",
                "NIOCore",
                "CNIOPosix",
                "DequeModule-product",
                "Atomics-product",
            ],
            "OrderedCollections-product": ["OrderedCollections", "InternalCollectionsUtilities"],
            "CNIOExtrasZlib": [],
            "_AtomicsShims": [],
            "OpenAPIKit-product": ["OpenAPIKit", "OpenAPIKitCore"],
            "Atomics-product": ["Atomics", "_AtomicsShims"],
            "CSystem": [],
            "HTTPTypes": [],
            "TSCBasic": ["TSCLibc", "TSCclibc"],
            "OpenAPIKit30": ["OpenAPIKitCore"],
            "NIOHTTP2-product": [
                "NIOHTTP2",
                "NIOHPACK",
                "NIO-product",
                "NIOCore-product",
                "NIOConcurrencyHelpers-product",
                "NIOHTTP1-product",
                "NIOTLS-product",
                "Atomics-product",
            ],
            "CNIOLinux": [],
            "NIOFoundationCompat-product": [
                "NIOFoundationCompat",
                "CNIOAtomics",
                "NIOConcurrencyHelpers",
                "_NIOBase64",
                "CNIODarwin",
                "CNIOLinux",
                "CNIOWindows",
                "CNIOWASI",
                "_NIODataStructures",
                "NIOCore",
                "NIOEmbedded",
                "CNIOPosix",
                "NIOPosix",
                "NIO",
                "DequeModule-product",
                "Atomics-product",
            ],
            "Algorithms-product": ["Algorithms", "RealModule-product"],
            "CYaml": [],
            "AllExcludingTests": [
                "swiftly_SwiftlyTests",
                "swiftly-product",
                "test-swiftly-product",
                "generate-docs-reference-product",
                "generate-command-models-product",
                "build-swiftly-release-product",
                "Swiftly",
                "TestSwiftly",
                "generate-docs-reference",
                "generate-command-models",
                "build-swiftly-release",
                "SwiftlyWebsiteAPI",
                "SwiftlyDownloadAPI",
                "SwiftlyDocs",
                "SwiftlyCore",
                "MacOSPlatform",
                "GenerateDocsReference",
                "GenerateCommandModels",
            ],
            "NIOCore-product": [
                "NIOCore",
                "CNIOAtomics",
                "NIOConcurrencyHelpers",
                "_NIOBase64",
                "CNIODarwin",
                "CNIOLinux",
                "CNIOWindows",
                "CNIOWASI",
                "_NIODataStructures",
                "DequeModule-product",
                "Atomics-product",
            ],
            "NIOTLS": [
                "CNIOAtomics",
                "NIOConcurrencyHelpers",
                "_NIOBase64",
                "CNIODarwin",
                "CNIOLinux",
                "CNIOWindows",
                "CNIOWASI",
                "_NIODataStructures",
                "NIOCore",
                "NIOEmbedded",
                "CNIOPosix",
                "NIOPosix",
                "NIO",
                "DequeModule-product",
                "Atomics-product",
            ],
            "OpenAPIGenerator-product": ["OpenAPIGenerator"],
            "Instrumentation": ["ServiceContextModule-product"],
            "NIOTransportServices": [
                "NIO-product",
                "NIOCore-product",
                "NIOFoundationCompat-product",
                "NIOTLS-product",
                "Atomics-product",
            ],
            "OpenAPIAsyncHTTPClient": [
                "OpenAPIRuntime-product",
                "HTTPTypes-product",
                "AsyncHTTPClient-product",
                "NIOFoundationCompat-product",
            ],
            "ServiceContextModule": [],
            "NIOHTTPCompression": ["CNIOExtrasZlib", "NIO-product", "NIOCore-product", "NIOHTTP1-product"],
            "NIOFoundationCompat": [
                "CNIOAtomics",
                "NIOConcurrencyHelpers",
                "_NIOBase64",
                "CNIODarwin",
                "CNIOLinux",
                "CNIOWindows",
                "CNIOWASI",
                "_NIODataStructures",
                "NIOCore",
                "NIOEmbedded",
                "CNIOPosix",
                "NIOPosix",
                "NIO",
                "DequeModule-product",
                "Atomics-product",
            ],
            "CNIOWindows": [],
            "ArgumentParserToolInfo": [],
            "CNIOPosix": [],
            "NIOTLS-product": [
                "NIOTLS",
                "CNIOAtomics",
                "NIOConcurrencyHelpers",
                "_NIOBase64",
                "CNIODarwin",
                "CNIOLinux",
                "CNIOWindows",
                "CNIOWASI",
                "_NIODataStructures",
                "NIOCore",
                "NIOEmbedded",
                "CNIOPosix",
                "NIOPosix",
                "NIO",
                "DequeModule-product",
                "Atomics-product",
            ],
            "Tracing": ["Instrumentation", "ServiceContextModule-product"],
            "_SubprocessCShims": [],
            "OrderedCollections": ["InternalCollectionsUtilities"],
            "NIOHTTP2": [
                "NIOHPACK",
                "NIO-product",
                "NIOCore-product",
                "NIOConcurrencyHelpers-product",
                "NIOHTTP1-product",
                "NIOTLS-product",
                "Atomics-product",
            ],
            "CNIODarwin": [],
            "InternalCollectionsUtilities": [],
            "Tracing-product": ["Tracing", "Instrumentation", "ServiceContextModule-product"],
            "CNIOWASI": [],
            "RealModule-product": ["RealModule", "_NumericsShims"],
            "_OpenAPIGeneratorCore": [
                "OpenAPIKit-product",
                "OpenAPIKit30-product",
                "OpenAPIKitCompat-product",
                "Algorithms-product",
                "OrderedCollections-product",
                "Yams-product",
            ],
            "SystemPackage": ["CSystem"],
            "_NIOFileSystem-product": [
                "_NIOFileSystem",
                "NIOFileSystem",
                "swift-nio__NIOFileSystem",
                "CNIOAtomics",
                "NIOConcurrencyHelpers",
                "_NIOBase64",
                "CNIODarwin",
                "CNIOLinux",
                "CNIOWindows",
                "CNIOWASI",
                "_NIODataStructures",
                "NIOCore",
                "CNIOPosix",
                "NIOPosix",
                "DequeModule-product",
                "Atomics-product",
                "SystemPackage-product",
            ],
            "NIO-product": [
                "NIO",
                "CNIOAtomics",
                "NIOConcurrencyHelpers",
                "_NIOBase64",
                "CNIODarwin",
                "CNIOLinux",
                "CNIOWindows",
                "CNIOWASI",
                "_NIODataStructures",
                "NIOCore",
                "NIOEmbedded",
                "CNIOPosix",
                "NIOPosix",
                "DequeModule-product",
                "Atomics-product",
            ],
            "ArgumentParser-product": ["ArgumentParser", "ArgumentParserToolInfo"],
            "OpenAPIKitCore": [],
            "build-swiftly-release": [
                "OpenAPIGenerator-product",
                "SwiftlyDownloadAPI",
                "SwiftlyWebsiteAPI",
                "generate-command-models-product",
                "GenerateCommandModels",
                "SwiftlyCore",
                "CLibArchive",
                "MacOSPlatform",
                "OpenAPIRuntime-product",
                "ArgumentParser-product",
                "SystemPackage-product",
                "AsyncHTTPClient-product",
                "NIOFoundationCompat-product",
                "OpenAPIAsyncHTTPClient-product",
                "Subprocess-product",
                "_NIOFileSystem-product",
            ],
            "swift-nio-ssl_NIOSSL": [],
            "NIOHPACK": ["NIO-product", "NIOCore-product", "NIOConcurrencyHelpers-product", "NIOHTTP1-product"],
            "NIOFileSystem": [
                "CNIOAtomics",
                "NIOConcurrencyHelpers",
                "_NIOBase64",
                "CNIODarwin",
                "CNIOLinux",
                "CNIOWindows",
                "CNIOWASI",
                "_NIODataStructures",
                "NIOCore",
                "CNIOPosix",
                "NIOPosix",
                "_NIOFileSystem",
                "DequeModule-product",
                "Atomics-product",
                "SystemPackage-product",
            ],
            "OpenAPIAsyncHTTPClient-product": [
                "OpenAPIAsyncHTTPClient",
                "OpenAPIRuntime-product",
                "HTTPTypes-product",
                "AsyncHTTPClient-product",
                "NIOFoundationCompat-product",
            ],
            "DequeModule-product": ["DequeModule", "InternalCollectionsUtilities"],
            "generate-command-models-product": ["ArgumentParser-product", "SystemPackage-product"],
            "NIOHTTP1": [
                "CNIOAtomics",
                "NIOConcurrencyHelpers",
                "_NIOBase64",
                "CNIODarwin",
                "CNIOLinux",
                "CNIOWindows",
                "CNIOWASI",
                "_NIODataStructures",
                "NIOCore",
                "NIOEmbedded",
                "CNIOPosix",
                "NIOPosix",
                "NIO",
                "CNIOLLHTTP",
                "DequeModule-product",
                "Atomics-product",
            ],
            "Atomics": ["_AtomicsShims"],
            "Logging": [],
            "Yams": ["CYaml"],
        ]
    }
}
