#if !canImport(ObjectiveC)
import XCTest

extension PIFBuilderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PIFBuilderTests = [
        ("testBinaryTargets", testBinaryTargets),
        ("testBuildSettings", testBuildSettings),
        ("testConditionalDependencies", testConditionalDependencies),
        ("testExecutableProducts", testExecutableProducts),
        ("testLibraryProducts", testLibraryProducts),
        ("testLibraryTargets", testLibraryTargets),
        ("testOrdering", testOrdering),
        ("testProject", testProject),
        ("testResources", testResources),
        ("testSystemLibraryTargets", testSystemLibraryTargets),
        ("testTestProducts", testTestProducts),
    ]
}

extension PIFTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PIFTests = [
        ("testEncodable", testEncodable),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PIFBuilderTests.__allTests__PIFBuilderTests),
        testCase(PIFTests.__allTests__PIFTests),
    ]
}
#endif
