#if !canImport(ObjectiveC)
import XCTest

extension BuildToolTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BuildToolTests = [
        ("testBinPathAndSymlink", testBinPathAndSymlink),
        ("testNonReachableProductsAndTargetsFunctional", testNonReachableProductsAndTargetsFunctional),
        ("testParseableInterfaces", testParseableInterfaces),
        ("testProductAndTarget", testProductAndTarget),
        ("testSeeAlso", testSeeAlso),
        ("testUsage", testUsage),
        ("testVersion", testVersion),
    ]
}

extension PackageToolTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PackageToolTests = [
        ("testDescribe", testDescribe),
        ("testDumpPackage", testDumpPackage),
        ("testInitCustomNameExecutable", testInitCustomNameExecutable),
        ("testInitEmpty", testInitEmpty),
        ("testInitExecutable", testInitExecutable),
        ("testInitLibrary", testInitLibrary),
        ("testMirrorConfig", testMirrorConfig),
        ("testPackageClean", testPackageClean),
        ("testPackageEditAndUnedit", testPackageEditAndUnedit),
        ("testPackageReset", testPackageReset),
        ("testPinning", testPinning),
        ("testPinningBranchAndRevision", testPinningBranchAndRevision),
        ("testResolve", testResolve),
        ("testSeeAlso", testSeeAlso),
        ("testShowDependencies", testShowDependencies),
        ("testSymlinkedDependency", testSymlinkedDependency),
        ("testUpdate", testUpdate),
        ("testUsage", testUsage),
        ("testVersion", testVersion),
        ("testWatchmanXcodeprojgen", testWatchmanXcodeprojgen),
    ]
}

extension RunToolTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RunToolTests = [
        ("testFileDeprecation", testFileDeprecation),
        ("testMultipleExecutableAndExplicitExecutable", testMultipleExecutableAndExplicitExecutable),
        ("testMutualExclusiveFlags", testMutualExclusiveFlags),
        ("testSanitizeThread", testSanitizeThread),
        ("testSeeAlso", testSeeAlso),
        ("testUnkownProductAndArgumentPassing", testUnkownProductAndArgumentPassing),
        ("testUnreachableExecutable", testUnreachableExecutable),
        ("testUsage", testUsage),
        ("testVersion", testVersion),
    ]
}

extension TestToolTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TestToolTests = [
        ("testNumWorkersParallelRequeriment", testNumWorkersParallelRequeriment),
        ("testNumWorkersValue", testNumWorkersValue),
        ("testSanitizeThread", testSanitizeThread),
        ("testSeeAlso", testSeeAlso),
        ("testUsage", testUsage),
        ("testVersion", testVersion),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BuildToolTests.__allTests__BuildToolTests),
        testCase(PackageToolTests.__allTests__PackageToolTests),
        testCase(RunToolTests.__allTests__RunToolTests),
        testCase(TestToolTests.__allTests__TestToolTests),
    ]
}
#endif
