#if !canImport(ObjectiveC)
import XCTest

extension AwaitTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AwaitTests = [
        ("testBasics", testBasics),
    ]
}

extension ByteStringTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ByteStringTests = [
        ("testAccessors", testAccessors),
        ("testAsString", testAsString),
        ("testByteStreamable", testByteStreamable),
        ("testDescription", testDescription),
        ("testHashable", testHashable),
        ("testInitializers", testInitializers),
    ]
}

extension CStringArrayTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CStringArrayTests = [
        ("testInitialization", testInitialization),
    ]
}

extension CacheableSequenceTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CacheableSequenceTests = [
        ("testBasics", testBasics),
    ]
}

extension CollectionAlgorithmsTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CollectionAlgorithmsTests = [
        ("testFindDuplicates", testFindDuplicates),
    ]
}

extension CollectionExtensionsTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CollectionExtensionsTests = [
        ("testOnly", testOnly),
    ]
}

extension ConditionTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConditionTests = [
        ("testBroadcast", testBroadcast),
        ("testSignal", testSignal),
        ("testWaitUntil", testWaitUntil),
    ]
}

extension DeltaAlgorithmTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DeltaAlgorithmTests = [
        ("testBasics", testBasics),
    ]
}

extension DiagnosticsEngineTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DiagnosticsEngineTests = [
        ("testBasics", testBasics),
        ("testHandlers", testHandlers),
        ("testMerging", testMerging),
    ]
}

extension DictionaryExtensionTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DictionaryExtensionTests = [
        ("testBasics", testBasics),
        ("testCreateDictionary", testCreateDictionary),
    ]
}

extension DictionaryLiteralExtensionsTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DictionaryLiteralExtensionsTests = [
        ("testDescription", testDescription),
        ("testEquality", testEquality),
    ]
}

extension EditDistanceTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EditDistanceTests = [
        ("testBasics", testBasics),
    ]
}

extension FileSystemTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FileSystemTests = [
        ("testInMemoryBasics", testInMemoryBasics),
        ("testInMemoryCreateDirectory", testInMemoryCreateDirectory),
        ("testInMemoryFsCopy", testInMemoryFsCopy),
        ("testInMemoryReadWriteFile", testInMemoryReadWriteFile),
        ("testInMemRemoveFileTree", testInMemRemoveFileTree),
        ("testLocalBasics", testLocalBasics),
        ("testLocalCreateDirectory", testLocalCreateDirectory),
        ("testLocalExistsSymlink", testLocalExistsSymlink),
        ("testLocalReadWriteFile", testLocalReadWriteFile),
        ("testRemoveFileTree", testRemoveFileTree),
        ("testRootedFileSystem", testRootedFileSystem),
        ("testSetAttribute", testSetAttribute),
    ]
}

extension GraphAlgorithmsTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GraphAlgorithmsTests = [
        ("testCycleDetection", testCycleDetection),
        ("testTopologicalSort", testTopologicalSort),
        ("testTransitiveClosure", testTransitiveClosure),
    ]
}

extension JSONMapperTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONMapperTests = [
        ("testBasics", testBasics),
        ("testErrors", testErrors),
    ]
}

extension JSONTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONTests = [
        ("testDecoding", testDecoding),
        ("testEncoding", testEncoding),
        ("testPrettyPrinting", testPrettyPrinting),
        ("testStringInitalizer", testStringInitalizer),
    ]
}

extension KeyedPairTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KeyedPairTests = [
        ("testBasics", testBasics),
    ]
}

extension LazyCacheTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LazyCacheTests = [
        ("testBasics", testBasics),
    ]
}

extension LockTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LockTests = [
        ("testBasics", testBasics),
        ("testFileLock", testFileLock),
    ]
}

extension ObjectIdentifierProtocolTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ObjectIdentifierProtocolTests = [
        ("testBasics", testBasics),
    ]
}

extension OrderedDictionaryTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OrderedDictionaryTests = [
        ("testBasics", testBasics),
    ]
}

extension OrderedSetTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OrderedSetTests = [
        ("testBasics", testBasics),
    ]
}

extension OutputByteStreamTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OutputByteStreamTests = [
        ("testBasics", testBasics),
        ("testBufferCorrectness", testBufferCorrectness),
        ("testFormattedOutput", testFormattedOutput),
        ("testJSONEncoding", testJSONEncoding),
        ("testLocalFileStream", testLocalFileStream),
        ("testStreamOperator", testStreamOperator),
        ("testThreadSafeStream", testThreadSafeStream),
    ]
}

extension POSIXTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__POSIXTests = [
        ("testFileStatus", testFileStatus),
    ]
}

extension PathShimTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PathShimTests = [
        ("testCurrentWorkingDirectory", testCurrentWorkingDirectory),
        ("testRescursiveDirectoryCreation", testRescursiveDirectoryCreation),
        ("testResolvingSymlinks", testResolvingSymlinks),
    ]
}

extension PathTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PathTests = [
        ("testAbsolutePathValidation", testAbsolutePathValidation),
        ("testBaseNameExtraction", testBaseNameExtraction),
        ("testBasics", testBasics),
        ("testCodable", testCodable),
        ("testCombinationsAndEdgeCases", testCombinationsAndEdgeCases),
        ("testComparison", testComparison),
        ("testConcatenation", testConcatenation),
        ("testContains", testContains),
        ("testDirectoryNameExtraction", testDirectoryNameExtraction),
        ("testDotDotPathComponents", testDotDotPathComponents),
        ("testDotPathComponents", testDotPathComponents),
        ("testParentDirectory", testParentDirectory),
        ("testPathComponents", testPathComponents),
        ("testRelativePathFromAbsolutePaths", testRelativePathFromAbsolutePaths),
        ("testRelativePathValidation", testRelativePathValidation),
        ("testRepeatedPathSeparators", testRepeatedPathSeparators),
        ("testStringInitialization", testStringInitialization),
        ("testStringLiteralInitialization", testStringLiteralInitialization),
        ("testSuffixExtraction", testSuffixExtraction),
        ("testTrailingPathSeparators", testTrailingPathSeparators),
    ]
}

extension ProcessSetTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ProcessSetTests = [
        ("testSigInt", testSigInt),
        ("testSigKillEscalation", testSigKillEscalation),
    ]
}

extension ProcessTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ProcessTests = [
        ("testBasics", testBasics),
        ("testCheckNonZeroExit", testCheckNonZeroExit),
        ("testFindExecutable", testFindExecutable),
        ("testNonExecutableLaunch", testNonExecutableLaunch),
        ("testPopen", testPopen),
        ("testSignals", testSignals),
        ("testStdoutStdErr", testStdoutStdErr),
        ("testThreadSafetyOnWaitUntilExit", testThreadSafetyOnWaitUntilExit),
    ]
}

extension RegExTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RegExTests = [
        ("testErrors", testErrors),
        ("testMatchGroups", testMatchGroups),
    ]
}

extension ResultTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ResultTests = [
        ("testAnyError", testAnyError),
        ("testBasics", testBasics),
        ("testFlatMap", testFlatMap),
        ("testMap", testMap),
        ("testMapAny", testMapAny),
    ]
}

extension SHA256Tests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SHA256Tests = [
        ("testBasics", testBasics),
        ("testLargeData", testLargeData),
    ]
}

extension SortedArrayTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SortedArrayTests = [
        ("testSortedArrayInAscendingOrder", testSortedArrayInAscendingOrder),
        ("testSortedArrayInDescendingOrder", testSortedArrayInDescendingOrder),
        ("testSortedArrayInsertIntoSmallerArray", testSortedArrayInsertIntoSmallerArray),
        ("testSortedArrayInsertSlice", testSortedArrayInsertSlice),
        ("testSortedArrayWithValues", testSortedArrayWithValues),
    ]
}

extension StringConversionTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringConversionTests = [
        ("testShellEscaped", testShellEscaped),
    ]
}

extension SyncronizedQueueTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SyncronizedQueueTests = [
        ("testMultipleProducerConsumer", testMultipleProducerConsumer),
        ("testMultipleProducerConsumer2", testMultipleProducerConsumer2),
        ("testSingleProducerConsumer", testSingleProducerConsumer),
    ]
}

extension TemporaryFileTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TemporaryFileTests = [
        ("testBasicReadWrite", testBasicReadWrite),
        ("testBasicTemporaryDirectory", testBasicTemporaryDirectory),
        ("testCanCreateUniqueTempDirectories", testCanCreateUniqueTempDirectories),
        ("testCanCreateUniqueTempFiles", testCanCreateUniqueTempFiles),
        ("testLeaks", testLeaks),
        ("testNoCleanupTemporaryFile", testNoCleanupTemporaryFile),
    ]
}

extension TerminalControllerTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TerminalControllerTests = [
        ("testBasic", testBasic),
    ]
}

extension ThreadTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ThreadTests = [
        ("testMultipleThread", testMultipleThread),
        ("testNotDeinitBeforeExecutingTask", testNotDeinitBeforeExecutingTask),
        ("testSingleThread", testSingleThread),
    ]
}

extension TupleTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TupleTests = [
        ("testBasics", testBasics),
    ]
}

extension WalkTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WalkTests = [
        ("testNonRecursive", testNonRecursive),
        ("testRecursive", testRecursive),
        ("testSymlinksNotWalked", testSymlinksNotWalked),
        ("testWalkingADirectorySymlinkResolvesOnce", testWalkingADirectorySymlinkResolvesOnce),
    ]
}

extension miscTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__miscTests = [
        ("testEmptyEnvSearchPaths", testEmptyEnvSearchPaths),
        ("testEnvSearchPaths", testEnvSearchPaths),
        ("testExecutableLookup", testExecutableLookup),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AwaitTests.__allTests__AwaitTests),
        testCase(ByteStringTests.__allTests__ByteStringTests),
        testCase(CStringArrayTests.__allTests__CStringArrayTests),
        testCase(CacheableSequenceTests.__allTests__CacheableSequenceTests),
        testCase(CollectionAlgorithmsTests.__allTests__CollectionAlgorithmsTests),
        testCase(CollectionExtensionsTests.__allTests__CollectionExtensionsTests),
        testCase(ConditionTests.__allTests__ConditionTests),
        testCase(DeltaAlgorithmTests.__allTests__DeltaAlgorithmTests),
        testCase(DiagnosticsEngineTests.__allTests__DiagnosticsEngineTests),
        testCase(DictionaryExtensionTests.__allTests__DictionaryExtensionTests),
        testCase(DictionaryLiteralExtensionsTests.__allTests__DictionaryLiteralExtensionsTests),
        testCase(EditDistanceTests.__allTests__EditDistanceTests),
        testCase(FileSystemTests.__allTests__FileSystemTests),
        testCase(GraphAlgorithmsTests.__allTests__GraphAlgorithmsTests),
        testCase(JSONMapperTests.__allTests__JSONMapperTests),
        testCase(JSONTests.__allTests__JSONTests),
        testCase(KeyedPairTests.__allTests__KeyedPairTests),
        testCase(LazyCacheTests.__allTests__LazyCacheTests),
        testCase(LockTests.__allTests__LockTests),
        testCase(ObjectIdentifierProtocolTests.__allTests__ObjectIdentifierProtocolTests),
        testCase(OrderedDictionaryTests.__allTests__OrderedDictionaryTests),
        testCase(OrderedSetTests.__allTests__OrderedSetTests),
        testCase(OutputByteStreamTests.__allTests__OutputByteStreamTests),
        testCase(POSIXTests.__allTests__POSIXTests),
        testCase(PathShimTests.__allTests__PathShimTests),
        testCase(PathTests.__allTests__PathTests),
        testCase(ProcessSetTests.__allTests__ProcessSetTests),
        testCase(ProcessTests.__allTests__ProcessTests),
        testCase(RegExTests.__allTests__RegExTests),
        testCase(ResultTests.__allTests__ResultTests),
        testCase(SHA256Tests.__allTests__SHA256Tests),
        testCase(SortedArrayTests.__allTests__SortedArrayTests),
        testCase(StringConversionTests.__allTests__StringConversionTests),
        testCase(SyncronizedQueueTests.__allTests__SyncronizedQueueTests),
        testCase(TemporaryFileTests.__allTests__TemporaryFileTests),
        testCase(TerminalControllerTests.__allTests__TerminalControllerTests),
        testCase(ThreadTests.__allTests__ThreadTests),
        testCase(TupleTests.__allTests__TupleTests),
        testCase(WalkTests.__allTests__WalkTests),
        testCase(miscTests.__allTests__miscTests),
    ]
}
#endif
