#if !canImport(ObjectiveC)
import XCTest

extension FSWatchTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FSWatchTests = [
        ("testBasics", testBasics),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FSWatchTests.__allTests__FSWatchTests),
    ]
}
#endif
