#if !canImport(ObjectiveC)
import XCTest

extension TestSupportTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TestSupportTests = [
        ("testAssertMatchStringLists", testAssertMatchStringLists),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TestSupportTests.__allTests__TestSupportTests),
    ]
}
#endif
