#if !canImport(ObjectiveC)
import XCTest

extension TSCTestSupportTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TSCTestSupportTests = [
        ("testAssertMatchStringLists", testAssertMatchStringLists),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TSCTestSupportTests.__allTests__TSCTestSupportTests),
    ]
}
#endif
