#if !canImport(ObjectiveC)
import XCTest

extension ReaddirTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReaddirTests = [
        ("testName", testName),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ReaddirTests.__allTests__ReaddirTests),
    ]
}
#endif
