//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift open source project
//
// Copyright (c) 2026 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See http://swift.org/LICENSE.txt for license information
// See http://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

import Vapor

/// An [RFC 7807] "problem details" error object used to convey error
/// responses from the package registry.
///
/// §3.3 (*Error handling*) of the Swift Package Registry Service
/// Specification requires that servers communicate any errors using
/// problem detail objects, serialized as `application/problem+json`, for
/// example:
///
/// ```http
/// HTTP/1.1 404
/// Content-Version: 1
/// Content-Type: application/problem+json
/// Content-Language: en
///
/// {
///    "detail": "release not found"
/// }
/// ```
///
/// The shape of the type follows the RFC 7807 problem details object.
/// Because it conforms to `Error`, a value can be thrown from a route
/// handler and intercepted by ``ProblemErrorMiddleware``, which
/// serializes it to a problem+json response with the appropriate
/// `status`, `Content-Type`, `Content-Language`, and `Content-Version`
/// headers.
///
/// Convenience factories such as ``notFound(_:)``, ``conflict(_:)``,
/// ``badRequest(_:)``, ``unprocessable(_:)``, and
/// ``unsupportedMediaType(_:)`` cover the status codes most commonly
/// returned by the registry API.
///
/// [RFC 7807]: https://www.rfc-editor.org/rfc/rfc7807
public struct ProblemDetails: Error, Sendable {
    /// A URI reference that identifies the problem type. Optional per
    /// RFC 7807.
    public var type: String?
    /// A short, human-readable summary of the problem type. Defaults to
    /// the reason phrase of ``status`` when not supplied explicitly.
    public var title: String?
    /// The HTTP status code generated by the origin server for this
    /// occurrence of the problem.
    public var status: HTTPResponseStatus
    /// A human-readable explanation specific to this occurrence of the
    /// problem, for example `"release not found"`.
    public var detail: String?
    /// A URI reference that identifies the specific occurrence of the
    /// problem.
    public var instance: String?

    /// Creates a `ProblemDetails` value.
    ///
    /// - Parameters:
    ///   - status: The HTTP status to associate with the problem. This
    ///     also determines the HTTP status code of the response produced
    ///     by ``ProblemErrorMiddleware``.
    ///   - title: A short, human-readable summary of the problem type. If
    ///     omitted, the reason phrase of `status` (for example,
    ///     `"Not Found"`) is used.
    ///   - detail: A human-readable explanation specific to this
    ///     occurrence.
    ///   - type: An optional URI reference identifying the problem type.
    ///   - instance: An optional URI reference identifying this specific
    ///     occurrence.
    public init(
        status: HTTPResponseStatus,
        title: String? = nil,
        detail: String? = nil,
        type: String? = nil,
        instance: String? = nil
    ) {
        self.status = status
        self.title = title ?? status.reasonPhrase
        self.detail = detail
        self.type = type
        self.instance = instance
    }
}

extension ProblemDetails: Encodable {
    private enum CodingKeys: String, CodingKey {
        case type, title, status, detail, instance
    }

    /// Encodes the problem to JSON in the shape required by RFC 7807.
    ///
    /// ``status`` is emitted as a numeric HTTP status code (for example,
    /// `404`) rather than as a Swift enum value. Optional fields are
    /// omitted when `nil` so the payload stays minimal.
    ///
    /// - Parameter encoder: The encoder to serialize into.
    /// - Throws: Any error thrown by the encoder's keyed container.
    public func encode(to encoder: Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encode(Int(status.code), forKey: .status)
        try c.encodeIfPresent(type, forKey: .type)
        try c.encodeIfPresent(title, forKey: .title)
        try c.encodeIfPresent(detail, forKey: .detail)
        try c.encodeIfPresent(instance, forKey: .instance)
    }
}

extension ProblemDetails {
    /// Builds a `404 Not Found` problem, for example for a release that
    /// does not exist at the requested `{scope}/{name}/{version}` URI.
    ///
    /// - Parameter detail: A human-readable explanation of the missing
    ///   resource.
    /// - Returns: A problem with status `.notFound`.
    public static func notFound(_ detail: String) -> ProblemDetails {
        ProblemDetails(status: .notFound, detail: detail)
    }

    /// Builds a `409 Conflict` problem, used when a request would
    /// conflict with existing state, for example attempting to
    /// re-publish an already-published release.
    ///
    /// - Parameter detail: A human-readable explanation of the conflict.
    /// - Returns: A problem with status `.conflict`.
    public static func conflict(_ detail: String) -> ProblemDetails {
        ProblemDetails(status: .conflict, detail: detail)
    }

    /// Builds a `400 Bad Request` problem, used for malformed requests
    /// such as an `Accept` header with an unparseable version component
    /// (§3.5 *API versioning*).
    ///
    /// - Parameter detail: A human-readable explanation of why the
    ///   request was rejected.
    /// - Returns: A problem with status `.badRequest`.
    public static func badRequest(_ detail: String) -> ProblemDetails {
        ProblemDetails(status: .badRequest, detail: detail)
    }

    /// Builds a `422 Unprocessable Entity` problem, used when a request
    /// is well-formed at the HTTP level but semantically invalid, for
    /// example publishing with an invalid manifest or metadata JSON.
    ///
    /// - Parameter detail: A human-readable explanation of the
    ///   validation failure.
    /// - Returns: A problem with status `.unprocessableEntity`.
    public static func unprocessable(_ detail: String) -> ProblemDetails {
        ProblemDetails(status: .unprocessableEntity, detail: detail)
    }

    /// Builds a `415 Unsupported Media Type` problem, used when the
    /// `Accept` header specifies a valid but unsupported API version
    /// (§3.5 *API versioning*).
    ///
    /// - Parameter detail: A human-readable explanation of the
    ///   unsupported media type.
    /// - Returns: A problem with status `.unsupportedMediaType`.
    public static func unsupportedMediaType(_ detail: String) -> ProblemDetails {
        ProblemDetails(status: .unsupportedMediaType, detail: detail)
    }
}
