//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift open source project
//
// Copyright (c) 2015-2016 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See http://swift.org/LICENSE.txt for license information
// See http://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

import ArgumentParser
import Basics

@_spi(SwiftPMInternal)
import CoreCommands

import Foundation
import PackageGraph
import PackageModel

@_spi(SwiftPMInternal)
import SPMBuildCore

import enum TSCBasic.ProcessEnv

import enum TSCUtility.Diagnostics

#if canImport(Android)
import Android
#endif

/// An enumeration of the errors that can be generated by the run tool.
private enum RunError: Swift.Error {
    /// The package manifest has no executable product.
    case noExecutableFound

    /// Could not find a specific executable in the package manifest.
    case executableNotFound(String)

    /// There are multiple executables and one must be chosen.
    case multipleExecutables([String])
}

extension RunError: CustomStringConvertible {
    var description: String {
        switch self {
        case .noExecutableFound:
            return "no executable product available"
        case .executableNotFound(let executable):
            return "no executable product named '\(executable)'"
        case .multipleExecutables(let executables):
            let joinedExecutables = executables.joined(separator: ", ")
            return "multiple executable products available: \(joinedExecutables)"
        }
    }
}

struct RunCommandOptions: ParsableArguments {
    enum RunMode: EnumerableFlag {
        case repl
        case debugger
        case run

        static func help(for value: RunCommandOptions.RunMode) -> ArgumentHelp? {
            switch value {
            case .repl:
                return "Launch Swift REPL for the package."
            case .debugger:
                return "Launch the executable in a debugger session."
            case .run:
                return "Launch the executable with the provided arguments."
            }
        }
    }

    /// The mode in with the tool command should run.
    @Flag var mode: RunMode = .run

    /// If the executable product should be built before running.
    @Flag(name: .customLong("skip-build"), help: "Skip building the executable product.")
    var shouldSkipBuild: Bool = false

    var shouldBuild: Bool { !shouldSkipBuild }

    /// If the test should be built.
    @Flag(name: .customLong("build-tests"), help: "Build both source and test targets.")
    var shouldBuildTests: Bool = false

    /// The executable product to run.
    @Argument(help: "The executable to run.", completion: .shellCommand("swift package completion-tool list-executables"))
    var executable: String?

    /// Select a specific workspace member by identity. Requires a
    /// `Workspace.swift` to be discoverable; disambiguates executable
    /// name collisions between members and scopes the lookup to that
    /// member's declared executables.
    @Option(
        name: .customLong("package"),
        help: "Select a specific workspace member by identity.",
    )
    var selectedPackage: PackageIdentity?

    /// The arguments to pass to the executable.
    @Argument(parsing: .captureForPassthrough,
              help: "The arguments to pass to the executable.")
    var arguments: [String] = []
}

/// The outcome of `resolveRunTarget`: the executable product name to
/// build and run, plus an optional workspace member identity to scope
/// the build subset to (nil when the resolved product is the only
/// candidate or the workspace has a single member).
public struct ResolvedRunTarget: Equatable, Sendable {
    public let productName: String
    public let packageFocus: PackageIdentity?

    public init(productName: String, packageFocus: PackageIdentity?) {
        self.productName = productName
        self.packageFocus = packageFocus
    }
}

extension RunCommandOptions {
    /// Pure decision logic for translating command-line options + Case
    /// A focus + `--package` selector into a `ResolvedRunTarget`.
    /// Extracted for direct unit testing; wired into the run/debugger
    /// paths by the instance method
    /// `SwiftRunCommand.resolveRunTarget(graph:swiftCommandState:)`.
    ///
    /// Ordering:
    /// 1. `--package` is validated first — outside a workspace it
    ///    emits `packageSelectorRequiresWorkspace`; unknown identity
    ///    emits `unknownWorkspaceMember`.
    /// 2. Scope selection: `--package X` restricts to X; else Case A
    ///    focus restricts to the enclosing member; else search across
    ///    all workspace members.
    /// 3. When the caller supplied an executable name:
    ///    - Not found in scope → `executableNotFoundInMember` (scoped)
    ///      or `executableNotFoundInWorkspace` (unscoped).
    ///    - Multiple candidates across members (unscoped only) →
    ///      `ambiguousExecutable`.
    /// 4. When no executable name was supplied:
    ///    - No candidates in scope → `noExecutableFoundInWorkspace`.
    ///    - More than one candidate in scope →
    ///      `multipleExecutablesInWorkspace`.
    ///
    /// The `packageFocus` field on the result is populated whenever
    /// the resolution was scoped to a specific member (by `--package`,
    /// Case A, or single-candidate disambiguation); the caller uses
    /// it to scope the build subset to that member.
    @_spi(SwiftPMInternal)
    public static func resolveRunTarget(
        requestedExecutable: String?,
        selectedPackage: PackageIdentity?,
        workspaceMemberFocus: PackageIdentity?,
        availableMemberIdentities: Set<PackageIdentity>?,
        executablesByMember: [PackageIdentity: [String]],
        observabilityScope: ObservabilityScope,
    ) -> ResolvedRunTarget? {
        // 1. Validate `--package` first.
        let resolvedPackage: PackageIdentity?
        if let selectedPackage {
            guard let availableMemberIdentities else {
                observabilityScope.emit(
                    .packageSelectorRequiresWorkspace(requested: selectedPackage),
                )
                return nil
            }
            guard availableMemberIdentities.contains(selectedPackage) else {
                observabilityScope.emit(
                    .unknownWorkspaceMember(
                        requested: selectedPackage,
                        known: availableMemberIdentities,
                    ),
                )
                return nil
            }
            resolvedPackage = selectedPackage
        } else {
            resolvedPackage = workspaceMemberFocus
        }

        // 2. Explicit-name resolution.
        if let requestedExecutable {
            if let scope = resolvedPackage {
                let members = executablesByMember[scope] ?? []
                guard members.contains(requestedExecutable) else {
                    observabilityScope.emit(
                        .executableNotFoundInMember(
                            requested: requestedExecutable,
                            package: scope,
                            known: Set(members.map(PackageIdentity.plain)),
                        ),
                    )
                    return nil
                }
                return ResolvedRunTarget(
                    productName: requestedExecutable,
                    packageFocus: scope,
                )
            }

            let matches = executablesByMember
                .flatMap { member, execs in
                    execs.filter { $0 == requestedExecutable }.map { (member, $0) }
                }
            if matches.isEmpty {
                let known = Dictionary(
                    uniqueKeysWithValues: executablesByMember.map { (member, execs) in
                        (member, Set(execs.map(PackageIdentity.plain)))
                    },
                )
                observabilityScope.emit(
                    .executableNotFoundInWorkspace(
                        requested: requestedExecutable,
                        known: known,
                    ),
                )
                return nil
            }
            if matches.count > 1 {
                observabilityScope.emit(
                    .ambiguousExecutable(
                        requested: requestedExecutable,
                        candidates: matches.map { (member: $0.0, product: $0.1) },
                    ),
                )
                return nil
            }
            let (member, product) = matches[0]
            return ResolvedRunTarget(productName: product, packageFocus: member)
        }

        // 3. Implicit resolution — collect candidates in scope.
        let candidates: [(member: PackageIdentity, product: String)]
        if let scope = resolvedPackage {
            candidates = (executablesByMember[scope] ?? []).map { (scope, $0) }
        } else {
            candidates = executablesByMember
                .flatMap { member, execs in execs.map { (member, $0) } }
        }

        if candidates.isEmpty {
            if let scope = resolvedPackage {
                observabilityScope.emit(.noExecutableFoundInMember(package: scope))
            } else {
                observabilityScope.emit(.noExecutableFoundInWorkspace())
            }
            return nil
        }
        if candidates.count > 1 {
            observabilityScope.emit(
                .multipleExecutablesInWorkspace(candidates: candidates),
            )
            return nil
        }
        return ResolvedRunTarget(
            productName: candidates[0].product,
            packageFocus: candidates[0].member,
        )
    }
}

/// swift-run command namespace
public struct SwiftRunCommand: AsyncSwiftCommand {
    public static var configuration = CommandConfiguration(
        commandName: "run",
        _superCommandName: "swift",
        abstract: "Build and run an executable product.",
        discussion: "SEE ALSO: swift build, swift package, swift test",
        version: SwiftVersion.current.completeDisplayString,
        helpNames: [.short, .long, .customLong("help", withSingleDash: true)])

    @OptionGroup()
    public var globalOptions: GlobalOptions

    @OptionGroup()
    var options: RunCommandOptions

    public var toolWorkspaceConfiguration: ToolWorkspaceConfiguration {
        return .init(wantsREPLProduct: options.mode == .repl)
    }

    public func run(_ swiftCommandState: SwiftCommandState) async throws {
        if options.shouldBuildTests && options.shouldSkipBuild {
            swiftCommandState.observabilityScope.emit(
              .mutuallyExclusiveArgumentsError(arguments: ["--build-tests", "--skip-build"])
            )
            throw ExitCode.failure
        }

        switch options.mode {
        case .repl:
            // Load a custom package graph which has a special product for REPL.
            let asyncUnsafeGraphLoader = {
                try await swiftCommandState.loadPackageGraph(
                    explicitProduct: self.options.executable
                )
            }

            // Construct the build operation.
            // FIXME: We need to implement the build tool invocation closure here so that build tool plugins work with the REPL. rdar://86112934
            let buildSystem = try await swiftCommandState.createBuildSystem(
                cacheBuildManifest: false,
                packageGraphLoader: asyncUnsafeGraphLoader
            )

            // Perform build.
            let buildResult = try await buildSystem.build(subset: .allExcludingTests(), buildOutputs: [.replArguments])
            guard let arguments = buildResult.replArguments else {
                swiftCommandState.observabilityScope.emit(error: "\(globalOptions.build.buildSystem) build system does not support this command")
                throw ExitCode.failure
            }

            // Execute the REPL.
            let interpreterPath = try swiftCommandState.getTargetToolchain().swiftInterpreterPath
            swiftCommandState.outputStream.send("Launching Swift (interpreter at \(interpreterPath)) REPL with arguments: \(arguments.joined(separator: " "))\n")
            swiftCommandState.outputStream.flush()
            try self.run(
                fileSystem: swiftCommandState.fileSystem,
                executablePath: interpreterPath,
                originalWorkingDirectory: swiftCommandState.originalWorkingDirectory,
                arguments: arguments,
                observabilityScope: swiftCommandState.observabilityScope
            )

        case .debugger:
            do {
                _ = try await swiftCommandState.getWorkspaceRoot()
                let buildSystem = try await swiftCommandState.createBuildSystem(
                    explicitProduct: options.executable,
                )
                let modulesGraph = try await buildSystem.getPackageGraph()
                guard let target = self.resolveRunTarget(
                    graph: modulesGraph,
                    swiftCommandState: swiftCommandState,
                ) else {
                    throw ExitCode.failure
                }
                let productName = target.productName
                if options.shouldBuildTests {
                    try await buildSystem.build(
                        subset: .allIncludingTests(package: target.packageFocus),
                        buildOutputs: [],
                    )
                } else if options.shouldBuild {
                    try await buildSystem.build(
                        subset: .product(productName, for: nil, package: target.packageFocus),
                        buildOutputs: [],
                    )
                }

                let productRelativePath = try swiftCommandState.productsBuildParameters.executablePath(for: productName)
                let productAbsolutePath = try await buildSystem.buildProductsPath(for: swiftCommandState.productsBuildParameters)
                    .appending(productRelativePath)

                // Make sure we are running from the original working directory.
                let cwd: AbsolutePath? = swiftCommandState.fileSystem.currentWorkingDirectory
                if cwd == nil || swiftCommandState.originalWorkingDirectory != cwd {
                    try ProcessEnv.chdir(swiftCommandState.originalWorkingDirectory)
                }

                if let debugger = try swiftCommandState.getTargetToolchain().swiftSDK.toolset.knownTools[.debugger],
                   let debuggerPath = debugger.path {
                    try self.run(
                        fileSystem: swiftCommandState.fileSystem,
                        executablePath: debuggerPath,
                        originalWorkingDirectory: swiftCommandState.originalWorkingDirectory,
                        arguments: debugger.extraCLIOptions + [productAbsolutePath.pathString] + options.arguments,
                        observabilityScope: swiftCommandState.observabilityScope
                    )
                } else {
                    let pathRelativeToWorkingDirectory = productAbsolutePath.relative(to: swiftCommandState.originalWorkingDirectory)
                    let lldbPath = try swiftCommandState.getTargetToolchain().getLLDB()
                    try safeExec(
                        path: lldbPath.pathString,
                        args: ["--", pathRelativeToWorkingDirectory.pathString] + options.arguments,
                        observabilityScope: swiftCommandState.observabilityScope
                    )
                }
            } catch Diagnostics.fatalError {
                throw ExitCode.failure
            } catch let error as RunError {
                swiftCommandState.observabilityScope.emit(error)
                throw ExitCode.failure
            }

        case .run:
            // Detect deprecated uses of swift run to interpret scripts.
            if let executable = options.executable, try isValidSwiftFilePath(fileSystem: swiftCommandState.fileSystem, path: executable) {
                swiftCommandState.observabilityScope.emit(.runFileDeprecation(filePath: executable))
                // Redirect execution to the toolchain's swift executable.
                let swiftInterpreterPath = try swiftCommandState.getTargetToolchain().swiftInterpreterPath
                // Prepend the script to interpret to the arguments.
                let arguments = [executable] + options.arguments
                try self.run(
                    fileSystem: swiftCommandState.fileSystem,
                    executablePath: swiftInterpreterPath,
                    originalWorkingDirectory: swiftCommandState.originalWorkingDirectory,
                    arguments: arguments,
                    observabilityScope: swiftCommandState.observabilityScope
                )
                return
            }

            do {
                _ = try await swiftCommandState.getWorkspaceRoot()
                let buildSystem = try await swiftCommandState.createBuildSystem(
                    explicitProduct: options.executable,
                )
                let modulesGraph = try await buildSystem.getPackageGraph()
                guard let target = self.resolveRunTarget(
                    graph: modulesGraph,
                    swiftCommandState: swiftCommandState,
                ) else {
                    throw ExitCode.failure
                }
                let productName = target.productName
                if options.shouldBuildTests {
                    try await buildSystem.build(
                        subset: .allIncludingTests(package: target.packageFocus),
                        buildOutputs: [],
                    )
                } else if options.shouldBuild {
                    try await buildSystem.build(
                        subset: .product(productName, for: nil, package: target.packageFocus),
                        buildOutputs: [],
                    )
                }

                let executablePath = try await buildSystem.buildProductsPath(for: swiftCommandState.productsBuildParameters)
                    .appending(component: productName)

                let productRelativePath = try swiftCommandState.productsBuildParameters.executablePath(for: productName)
                let productAbsolutePath = try await buildSystem.buildProductsPath(for: swiftCommandState.productsBuildParameters)
                    .appending(productRelativePath)

                let runnerPath: AbsolutePath
                let arguments: [String]

                if let debugger = try swiftCommandState.getTargetToolchain().swiftSDK.toolset.knownTools[.debugger],
                   let debuggerPath = debugger.path {
                    runnerPath = debuggerPath
                    arguments = debugger.extraCLIOptions + [productAbsolutePath.pathString] + options.arguments
                } else {
                    runnerPath = executablePath
                    arguments = options.arguments
                }

                try self.run(
                    fileSystem: swiftCommandState.fileSystem,
                    executablePath: runnerPath,
                    originalWorkingDirectory: swiftCommandState.originalWorkingDirectory,
                    arguments: arguments,
                    observabilityScope: swiftCommandState.observabilityScope
                )
            } catch Diagnostics.fatalError {
                throw ExitCode.failure
            } catch let error as RunError {
                swiftCommandState.observabilityScope.emit(error)
                throw ExitCode.failure
            }
        }
    }

    /// Bridge between the CLI-level state (workspace context + graph)
    /// and the pure `RunCommandOptions.resolveRunTarget`. In a
    /// workspace, delegates to the pure function with an
    /// `executablesByMember` map built from the loaded root packages.
    /// Outside a workspace, delegates to the pre-workspaces
    /// `findProductName` — its `RunError` diagnostics remain the
    /// appropriate UX for single-package invocations, except when
    /// `--package` was supplied, in which case we still route through
    /// the workspace-aware resolver to surface the
    /// `packageSelectorRequiresWorkspace` diagnostic.
    private func resolveRunTarget(
        graph: ModulesGraph,
        swiftCommandState: SwiftCommandState,
    ) -> ResolvedRunTarget? {
        let availableMembers = swiftCommandState.currentWorkspaceMemberIdentities

        if availableMembers == nil, options.selectedPackage == nil {
            do {
                let productName = try findProductName(in: graph)
                return ResolvedRunTarget(productName: productName, packageFocus: nil)
            } catch let error as RunError {
                swiftCommandState.observabilityScope.emit(error)
                return nil
            } catch {
                swiftCommandState.observabilityScope.emit(error)
                return nil
            }
        }

        let executablesByMember = Dictionary(
            uniqueKeysWithValues: graph.rootPackages.map { pkg -> (PackageIdentity, [String]) in
                let executables = pkg.products
                    .filter { $0.type == ProductType.executable || $0.type == ProductType.snippet }
                    .map(\.name)
                return (pkg.identity, executables)
            },
        )

        return RunCommandOptions.resolveRunTarget(
            requestedExecutable: options.executable,
            selectedPackage: options.selectedPackage,
            workspaceMemberFocus: swiftCommandState.currentWorkspaceMemberFocus,
            availableMemberIdentities: availableMembers,
            executablesByMember: executablesByMember,
            observabilityScope: swiftCommandState.observabilityScope,
        )
    }

    /// Returns the path to the correct executable based on options.
    private func findProductName(in graph: ModulesGraph) throws -> String {
        if let executable = options.executable {
            // There should be only one product with the given name in the graph
            // and it should be executable or snippet.
            guard let product = graph.product(for: executable),
                  product.type == .executable || product.type == .snippet
            else {
                throw RunError.executableNotFound(executable)
            }
            return executable
        }

        // If the executable is implicit, search through root products.
        let rootExecutables = graph.rootPackages
            .flatMap { $0.products }
            // The type checker slows down significantly when ProductTypes arent explicitly typed.
            .filter { $0.type == ProductType.executable || $0.type == ProductType.snippet }
            .map { $0.name }

        // Error out if the package contains no executables.
        guard rootExecutables.count > 0 else {
            throw RunError.noExecutableFound
        }

        // Only implicitly deduce the executable if it is the only one.
        guard rootExecutables.count == 1 else {
            throw RunError.multipleExecutables(rootExecutables)
        }

        return rootExecutables[0]
    }

    /// Executes the executable at the specified path.
    private func run(
        fileSystem: FileSystem,
        executablePath: AbsolutePath,
        originalWorkingDirectory: AbsolutePath,
        arguments: [String],
        observabilityScope: ObservabilityScope
    ) throws {
        // Make sure we are running from the original working directory.
        let cwd: AbsolutePath? = fileSystem.currentWorkingDirectory
        if cwd == nil || originalWorkingDirectory != cwd {
            try ProcessEnv.chdir(originalWorkingDirectory)
        }

        let pathRelativeToWorkingDirectory = executablePath.relative(to: originalWorkingDirectory)
        try safeExec(path: executablePath.pathString, args: [pathRelativeToWorkingDirectory.pathString] + arguments, observabilityScope: observabilityScope)
    }

    /// Determines if a path points to a valid swift file.
    private func isValidSwiftFilePath(fileSystem: FileSystem, path: String) throws -> Bool {
        guard path.hasSuffix(".swift") else { return false }
        //FIXME: Return false when the path is not a valid path string.
        let absolutePath: AbsolutePath
        if path.first == "/" {
            do {
                absolutePath = try AbsolutePath(validating: path)
            } catch {
                return false
            }
        } else {
            guard let cwd = fileSystem.currentWorkingDirectory else {
                return false
            }
            absolutePath = try AbsolutePath(cwd, validating: path)
        }
        return fileSystem.isFile(absolutePath)
    }

    public init() {}
}

private extension Basics.Diagnostic {
    static func runFileDeprecation(filePath: String) -> Self {
        .warning("'swift run \(filePath)' command to interpret swift files is deprecated; use 'swift \(filePath)' instead")
    }
}

