// swift-tools-version: 6.5;(experimentalCGen)

import PackageDescription

let package = Package(
    name: "swift-sdl",
    platforms: [.macOS(.v26)],
    products: [
        .library(
            name: "SDL",
            targets: ["SDL"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-argument-parser", from: "1.8.0"),
        .package(url: "https://github.com/swiftlang/swift-tools-support-core", branch: "main"),
        .package(url: "https://github.com/swiftlang/swift-subprocess", from: "0.5.0"),
        .package(url: "https://github.com/swiftlang/swift-syntax", from: "603.0.1"),
        .externalSource(path: "../SDL"),
    ],
    externals: [
        Package(
            name: "SDL",
            products: [
                .library(name: "SDL3", type: .static, targets: ["SDL3"]),
            ],
            targets: [
                .externalLibrary(
                    name: "SDL3",
                    cSettings: [
                        .publicHeaderPath("include"),
                    ],
                    linkerSettings: [
                        .linkedFramework("CoreMedia", .when(platforms: [.macOS])),
                        .linkedFramework("CoreVideo", .when(platforms: [.macOS])),
                        .linkedFramework("Cocoa", .when(platforms: [.macOS])),
                        .linkedFramework("UniformTypeIdentifiers", .when(platforms: [.macOS])),
                        .linkedFramework("IOKit", .when(platforms: [.macOS])),
                        .linkedFramework("ForceFeedback", .when(platforms: [.macOS])),
                        .linkedFramework("Carbon", .when(platforms: [.macOS])),
                        .linkedFramework("CoreAudio", .when(platforms: [.macOS])),
                        .linkedFramework("AudioToolbox", .when(platforms: [.macOS])),
                        .linkedFramework("AVFoundation", .when(platforms: [.macOS])),
                        .linkedFramework("Foundation", .when(platforms: [.macOS])),
                        .linkedFramework("GameController", .when(platforms: [.macOS])),
                        .linkedFramework("Metal", .when(platforms: [.macOS])),
                        .linkedFramework("QuartzCore", .when(platforms: [.macOS])),
                        .linkedFramework("CoreHaptics", .when(platforms: [.macOS]))
                    ]
                ),
            ],
            pluginUsages: [
                "CMakeBuilderPlugin",
            ]
        ),
    ],
    targets: [
        .target(
            name: "CSDL",
            dependencies: [
                .product(name: "SDL3", package: "SDL"),
            ],
            publicHeadersPath: ".",
            plugins: ["SDLAPIGenPlugin"]
        ),
        .target(
            // The Swift bindings which are generated by the plugin.
            name: "SDL",
            dependencies: ["CSDL"],
            plugins: ["SwiftSDLGenPlugin"]
        ),
        .target(
            // Common parts to the API Notes generator and the Swift Bindings generator.
            // Might be better to be the same generator and just different args.
            name: "SDLGenerator",
            dependencies: [
                .product(name: "Subprocess", package: "swift-subprocess"),
                .product(name: "SwiftSyntax", package: "swift-syntax"),
                .product(name: "SwiftParser", package: "swift-syntax"),
            ],
        ),
        .executableTarget(
            name: "SDLAPIGenerator",
            dependencies: ["SDLGenerator"]
        ),
        .plugin(
            name: "SDLAPIGenPlugin",
            capability: .buildTool,
            dependencies: ["SDLAPIGenerator"]
        ),
        .executableTarget(
            name: "SwiftSDLGenerator"
        ),
        .plugin(
            name: "SwiftSDLGenPlugin",
            capability: .buildTool,
            dependencies: ["SwiftSDLGenerator"]
        ),
        .testTarget(
            name: "SDLTests",
            dependencies: ["SDL"]
        ),
        .executableTarget(
            name: "CMakeBuilder",
            dependencies: [
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
                .product(name: "Subprocess", package: "swift-subprocess"),
                .product(name: "TSCBasic", package: "swift-tools-support-core"),
            ]
        ),
        .plugin(
            name: "CMakeBuilderPlugin",
            capability: .externalBuilder,
            dependencies: ["CMakeBuilder"]
        ),
    ],
)
