#import <Foundation/Foundation.h>

#import "include/ObjcResourceReader.h"

@implementation ObjcResourceReader

+ (NSString *)readResource:(NSString *)resource
                    ofType:(NSString *)type {
    // The `SWIFTPM_MODULE_BUNDLE` macro is generated by SwiftPM to provide
    // access to the target's bundled resources.
    NSBundle *moduleBundle = SWIFTPM_MODULE_BUNDLE;
    NSString *path = [moduleBundle pathForResource:resource ofType:type];
    return [[NSString alloc] initWithContentsOfFile:path
                                           encoding:NSUTF8StringEncoding
                                              error:nil];
}

@end
