import Foundation

public class SwiftResourceReader {
    public static func read(_ resource: String, type: String?) throws -> String {
        // The `Bundle.module` is generated by SwiftPM to provide access to the
        // target's bundled resources.
        let path = Bundle.module.path(forResource: resource, ofType: type)
        return try String(contentsOfFile: path!, encoding: .utf8)
    }
}
