#if !os(macOS)
import XCTest

extension GitRepositoryTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GitRepositoryTests = [
        ("testAlternativeObjectStoreValidation", testAlternativeObjectStoreValidation),
        ("testAreIgnored", testAreIgnored),
        ("testAreIgnoredWithSpaceInRepoPath", testAreIgnoredWithSpaceInRepoPath),
        ("testBranchOperations", testBranchOperations),
        ("testCheckoutRevision", testCheckoutRevision),
        ("testCheckouts", testCheckouts),
        ("testFetch", testFetch),
        ("testGitFileView", testGitFileView),
        ("testGitRepositoryHash", testGitRepositoryHash),
        ("testHasUnpushedCommits", testHasUnpushedCommits),
        ("testProvider", testProvider),
        ("testRawRepository", testRawRepository),
        ("testRepositorySpecifier", testRepositorySpecifier),
        ("testSetRemote", testSetRemote),
        ("testSubmoduleRead", testSubmoduleRead),
        ("testSubmodules", testSubmodules),
        ("testUncommitedChanges", testUncommitedChanges),
    ]
}

extension InMemoryGitRepositoryTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InMemoryGitRepositoryTests = [
        ("testBasics", testBasics),
        ("testProvider", testProvider),
    ]
}

extension RepositoryManagerTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RepositoryManagerTests = [
        ("testBasics", testBasics),
        ("testParallelLookups", testParallelLookups),
        ("testPersistence", testPersistence),
        ("testReset", testReset),
        ("testSkipUpdate", testSkipUpdate),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GitRepositoryTests.__allTests__GitRepositoryTests),
        testCase(InMemoryGitRepositoryTests.__allTests__InMemoryGitRepositoryTests),
        testCase(RepositoryManagerTests.__allTests__RepositoryManagerTests),
    ]
}
#endif
