#if !canImport(ObjectiveC)
import XCTest

extension VersionTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VersionTests = [
        ("testBasics", testBasics),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(VersionTests.__allTests__VersionTests),
    ]
}
#endif
