#if !os(macOS)
import XCTest

extension JSONTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONTests = [
        ("testEncoding", testEncoding),
    ]
}

extension VersionTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VersionTests = [
        ("testBasics", testBasics),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(JSONTests.__allTests__JSONTests),
        testCase(VersionTests.__allTests__VersionTests),
    ]
}
#endif
