#!/usr/bin/env bash

set -eu

# This source file is part of the Swift.org open source project
#
# Copyright (c) 2019 Apple Inc. and the Swift project authors
# Licensed under Apache License v2.0 with Runtime Library Exception
#
# See http://swift.org/LICENSE.txt for license information
# See http://swift.org/CONTRIBUTORS.txt for Swift project authors

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

SRCROOT="`cd "${__dir}/..";pwd`"
echo "SRCROOT is $SRCROOT"

IMPORT_DIR="`cd "${SRCROOT}/../swiftpm/swift-tools-support-core";pwd`"

echo Copying from $IMPORT_DIR
cp -r ${IMPORT_DIR}/* $SRCROOT
