// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "AppPlaygroundWithTests",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "AppPlaygroundWithTests",
            targets: ["AppPlaygroundWithTests"],
            bundleIdentifier: "com.apple.dt.tests.AppPlaygroundWithTests",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .earth),
            accentColor: .presetColor(.teal),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .entertainment
        )
    ],
    targets: [
        .executableTarget(
            name: "AppPlaygroundWithTests",
            path: "Sources"
        ),
        .testTarget(
            name: "AppTests",
            dependencies: [
                "AppPlaygroundWithTests"
            ],
            path: "Tests"
        )
    ]
)
