on:
  pull_request_target:
    types: [opened, edited, reopened, labeled, unlabeled, synchronize]

permissions:
  issues: read
  pull-requests: read

jobs:
  check_dependencies:
    name: "Check GitHub PR Dependencies"
    uses: swiftlang/github-workflows/.github/workflows/github_actions_dependencies.yml@0.0.11
