name: SwiftPM Test Matrix

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      buildSystem:
        type: string
        required: true
      executableTargetBuildSystem:
        type: string
        required: true
      linuxSwiftVersion:
        type: string
        required: true
      enableWindowsChecks:
        type: boolean
        required: true

jobs:

  matrix-test:
    name: Test (${{ inputs.buildSystem }}) (exectable target built using ${{ inputs.executableTargetBuildSystem }})
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@0.0.2
    with:
      linux_os_versions: '["amazonlinux2", "bookworm", "noble", "jammy", "rhel-ubi9"]'
      linux_swift_versions: ${{ inputs.linuxSwiftVersion }}
      linux_pre_build_command: ./.github/scripts/prebuild.sh
      linux_build_command: 'swift run --build-system ${{ inputs.executableTargetBuildSystem }} swift-build --build-tests && swift run --build-system ${{ inputs.executableTargetBuildSystem }} swift-test --parallel --build-system ${{ inputs.buildSystem}}'
      windows_swift_versions: '["nightly-main"]'
      windows_pre_build_command: 'Invoke-Program .\.github\scripts\prebuild.ps1'
      windows_build_command: 'Invoke-Program swift run --build-system ${{ inputs.executableTargetBuildSystem }} swift-build --build-tests && swift run --build-system ${{ inputs.executableTargetBuildSystem }} -Xlinker /ignore:4217 swift-test -Xlinker /ignore:4217 --parallel --build-system ${{ inputs.buildSystem}}'
      enable_windows_checks: ${{ inputs.enableWindowsChecks }}
      enable_ios_checks: true
      enable_macos_checks: true
      macos_exclude_xcode_versions: "[{\"xcode_version\": \"16.3\"}, {\"xcode_version\": \"16.4\"}]"
      macos_build_command: 'swift run --build-system ${{ inputs.executableTargetBuildSystem }} swift-build --build-tests && swift run --build-system ${{ inputs.executableTargetBuildSystem }} swift-test --parallel --build-system ${{ inputs.buildSystem}}'
      ios_build_command: 'swift run --build-system ${{ inputs.executableTargetBuildSystem }} swift-build --build-tests && swift run --build-system ${{ inputs.executableTargetBuildSystem }} swift-test --parallel --build-system ${{ inputs.buildSystem }} --sdk \"$(xcrun --sdk iphoneos --show-sdk-path)\" --triple arm64-apple-ios'
